/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Typedef for the Unifier substitution map
 * @author Oliver Dixon
 * @date 2026-01-23
 * @version Development
 */

#ifndef OPTIFOL_UNIFIER_HPP
#define OPTIFOL_UNIFIER_HPP

#include "../Optifol.hpp"
#include "../IR/Terms/Variable.hpp"

namespace optifol
{

class IProcessedTerm;

/**
 * @typedef Unifier
 * @brief An alias for a Variable-to-term substitution; typically generated by UnificationVisitor and consumed by
 *  UnificationApplicationVisitor.
 */
using Unifier = RawUnorderedMap<const Variable, const IProcessedTerm *>;

}

#endif // OPTIFOL_UNIFIER_HPP
