/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification for the Unifier substitution map
 * @author Oliver Dixon
 * @date 2026-01-23
 * @version Development
 */

#ifndef OPTIFOL_UNIFIER_HPP
#define OPTIFOL_UNIFIER_HPP

#include "../IR/Terms/Variable.hpp"
#include "../Optifol.hpp"

namespace optifol
{

class IProcessedTerm;

/**
 * @class Unifier
 * @brief A thin wrapper for Variable-to-term substitutions; typically generated by
 * BidirectionalUnificationVisitor and consumed by UnificationApplicationVisitor.
 */
struct Unifier : ISerialisable
{
    /**
     * @brief Construct an empty Unifier with no substitutions
     */
    Unifier();

    /**
     * @brief Construct a Unifier with an initial set of substitutions.
     * @param unifier The initial substitution set, mapping unique Variable term to IProcessedTerm objects.
     */
    // ReSharper disable once CppNonExplicitConvertingConstructor
    Unifier(RawUnorderedMap<const Variable, const IProcessedTerm *> unifier);

    /**
     * @brief Compare two Unifier instances according to the unordered substitutions.
     * @param other The other Unifier.
     * @return Do the two Unifier instances represent the same set of substitutions?
     */
    [[nodiscard]] bool operator==(const Unifier &other) const;

    /**
     * @brief Serialise the @f$ N @f$ Unifier substitutions @f$ \left( v_i \mapsto t_i \right) @f$ in the form
     *  @f$ \left\{ v_1 / t_1, \ldots, v_N / t_N \right\} @f$ to the given output stream.
     * @param ostream The destination output stream.
     * @return The populated output stream.
     */
    std::ostream &serialise(std::ostream &ostream) const override;

    [[nodiscard]] std::vector<std::string> split_serialise() const;

    /**
     * @brief The Unifier contents, wherein each entry represents a mapping between a Variable and an
     * IProcessedTerm.
     * @note The key and value are observing pointers to a SymbolRepository, and as such, require all the
     * usual lifetime guarantees conferred by a non-ephemeral SymbolRepository.
     */
    RawUnorderedMap<const Variable, const IProcessedTerm *> unifier;
};

} // namespace optifol

#endif // OPTIFOL_UNIFIER_HPP
