/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification for the TestResult results storage
 * @author Oliver Dixon
 * @date 2025-07-20
 * @version Development
 */

#ifndef TESTRESULT_HPP
#define TESTRESULT_HPP

#include <giomm/liststore.h>
#include <glibmm/ustring.h>
#include <optional>
#include <string>
#include <vector>

#include "../../IHashable.hpp"
#include "../Modelling/ITestModelNode.hpp"
#include "PartialTestResult.hpp"

namespace optifol
{

/**
 * @class TestResult
 * @brief Describes a single result provided by a software unit-testing framework. The TestResult is agnostic
 * to the framework, but does encode the test name, test fixture name, and executable path for which the
 * result is relevant.
 */
class TestResult : public IHashable,
                   public ITestModelNode
{
public:
    /**
     * @brief Create a new TestResult with the given name, result, execution time, and partial results.
     * @details Note that the test fixture name is not specified upon construction. This is due to a
     * requirement on many backend parsers that the fixture object is parsed after its constituent test
     * results. Therefore the fixture name is specified after construction with @ref
     * populate_test_fixture_name.
     * @param test_name The name of the individual test.
     * @param passed Did the test pass?
     * @param execution_time Running execution time of the test.
     * @param partial_results Partial results generated by the testing framework.
     */
    TestResult(Glib::ustring test_name, bool passed, std::size_t execution_time,
            std::vector<Glib::RefPtr<PartialTestResult>> &&partial_results = {});

    /**
     * @copybrief IHashable::hash
     * @return The hashcode of the TestResult object
     * @warning This hash function is incomplete. It will only uniquely identify the Test with which the
     * result is associated, according to the test name and fixture name. It does not consider the fabric of
     * the result.
     */
    [[nodiscard]] std::size_t hash() const noexcept override;

    [[nodiscard]] Glib::RefPtr<Gtk::TreeListModel> get_tests_tree() const noexcept override;

    [[nodiscard]] Glib::RefPtr<Gtk::TreeListModel> get_results_tree() const noexcept override;

    /**
     * @brief Endow the TestResult with the name of the fixture of the Test to which the TestResult relates.
     * @param incoming_fixture_name The fixture name.
     */
    void populate_test_fixture_name(const std::string &incoming_fixture_name);

    /**
     * @brief Get a copy of the Test name associated with the TestResult.
     * @return The name of the Test to which the TestResult relates.
     */
    [[nodiscard]] Glib::ustring copy_test_name() const noexcept;

    /**
     * @brief Queries the binary result.
     * @return Did the test pass?
     */
    [[nodiscard]] bool has_passed() const noexcept;

    /**
     * @brief Queries the test execution time.
     * @return Duration time for execution of the test.
     */
    [[nodiscard]] std::size_t get_execution_time() const noexcept;

    /**
     * @brief Get a copy of the fixture name of the Test associated with the TestResult.
     * @return The name of the fixture to which the TestResult relates.
     */
    [[nodiscard]] Glib::ustring copy_fixture_name() const noexcept;

    /**
     * @brief Compare two TestResult objects using only the associated test name and fixture name.
     * @param other The other TestResult.
     * @return Are the two TestResult objects relating to the same Test?
     */
    bool operator==(const TestResult &other) const noexcept;

    /**
     * @brief Compare a TestResult object with an explicit test name and fixture name.
     * @param names A @ref std::pair encoding of the fixture name followed by the test name.
     * @return Is the TestResult for the fixture-test Test specified by the pair?
     */
    bool operator==(const std::pair<Glib::ustring, Glib::ustring> &names) const noexcept;

private:
    const Glib::ustring test_name;
    Glib::ustring fixture_name;

    const bool passed;
    const std::size_t execution_time;

    const Glib::RefPtr<Gio::ListStore<PartialTestResult>> partial_results =
            Gio::ListStore<PartialTestResult>::create();
    const Glib::RefPtr<Gtk::TreeListModel> partial_results_tree =
            Gtk::TreeListModel::create(partial_results, &ITestModelNode::get_given_results_tree, true);
};

} // namespace optifol

template<>
struct std::hash<optifol::TestResult>
{
    using is_transparent = void;

    std::size_t operator()(const optifol::TestResult *object) const noexcept
    {
        return object->hash();
    }

    std::size_t operator()(const std::pair<Glib::ustring, Glib::ustring> &names) const noexcept
    {
        return optifol::IHashable::hash_combine(
                std::hash<std::string>{}(names.first), std::hash<std::string>{}(names.second));
    }

    std::size_t operator()(const optifol::TestResult &object) const noexcept
    {
        return object.hash();
    }

    std::size_t operator()(const std::shared_ptr<optifol::TestResult> &shared_hashable) const noexcept
    {
        return shared_hashable->hash();
    }
};

#endif // TESTRESULT_HPP
