/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class definition and implementation of static Google Test support
 * @author Oliver Dixon
 * @date 2025-06-14
 * @version Development
 */

#ifndef GOOGLETESTSUPPORT_HPP
#define GOOGLETESTSUPPORT_HPP

namespace optifol
{

// Current Clang 18 bug reports Doxygen violations for uses of @tparam on templated concepts.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"
/**
 * @concept GoogleTestable
 * @brief Represents a type that has good support for use in unit tests orchestrated by the Google Test framework.
 * @details In particular, a type <code>Candidate</code> with good support implements:
 *  <ul>
 *      <li>Equality comparison with <code>Candidate::operator==(const Candidate&)</code>;</li>
 *      <li>Inverse equality comparison with <code>Candidate::operator!=(const Candidate&)</code>, noting that this can
 *          often be generated by compilers given a valid equality operator overload;</li>
 *      <li>Stream-bound serialisation with <code>operator<<(std::ostream&, const Candidate&)</code>.</li>
 *  </ul>
 * @tparam Candidate The candidate for the concept properties
 */
template<typename Candidate>
concept GoogleTestable =
    requires(const Candidate& lhs, const Candidate& rhs, std::ostream& ostream)
{
    { lhs.operator==(rhs) } -> std::convertible_to<bool>; // For EXPECT_EQ, et al.
    { ostream << lhs } -> std::same_as<std::ostream&>; // For serialising 'actual' vs. 'expected' results on failure.
};
#pragma clang diagnostic pop

/**
 * @class GoogleTestSupport
 * @brief Provides static member functions to support Google Test assertions for Optifol types.
 */
class GoogleTestSupport
{
public:
    /**
     * @brief Assert equality on two GoogleTestable results
     * @tparam ActualType The type of the actual returned value
     * @tparam ExpectedType The type of the expected value
     * @param actual The actual returned value
     * @param expected The expected value
     */
    template<GoogleTestable ActualType, GoogleTestable ExpectedType>
    static void test_sentence_equality(const ActualType& actual, const ExpectedType& expected)
    {
        EXPECT_EQ(actual, expected);
    }
};

}

#endif
