/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification of the exposed first-order logic parser
 * @date 2024-11-21
 * @author Oliver Dixon <od641@york.ac.uk>
 * @note This file depends on build-time generated source from Flex and Bison.
 */

#ifndef FOLPARSER_HPP
#define FOLPARSER_HPP

#include <memory>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
#include <generated/BaseFOLParser.hpp> // Generated by Bison
#pragma clang diagnostic pop

#include "../Exceptions/ParseError.hpp"
#include "../IR/MutableVariants/Sentences/IMutableSentence.hpp"

namespace optifol
{

/**
 * @brief The first-order logic parser encapsulates the raw Bison-generated parser and provides various safety
 * and convenience mechanisms.
 */
class FOLParser : public impl::BaseFOLParser
{
public:
    /**
     * @brief Instantiate a new first-order logic parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     */
    explicit FOLParser(FOLLexer *lexer) :
        BaseFOLParser(lexer)
    {
    }

    void error(const std::string &msg) override
    {
        throw ParseError(msg, 0);
    }

    /**
     * @brief Reports a new fully parsed root sentence, typically from another parser-like source
     * @param sentence_root The parsed FOL sentence
     */
    [[maybe_unused]] void register_sentence(std::unique_ptr<MutableSentenceRoot> &&sentence_root)
    {
        last_parsed_root = std::move(sentence_root);
    }

    [[nodiscard]] std::unique_ptr<MutableSentenceRoot> retrieve_sentence()
    {
        auto sentence = std::move(last_parsed_root);
        last_parsed_root = nullptr;
        return sentence;
    }

private:
    std::unique_ptr<MutableSentenceRoot> last_parsed_root;
};

} // namespace optifol

#endif
