/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification of the exposed first-order logic parser
 * @date 2024-11-21
 * @author Oliver Dixon <od641@york.ac.uk>
 * @warning This file depends on build-time generated source from Flex and Bison.
 */

#ifndef FOLPARSER_HPP
#define FOLPARSER_HPP

#include <memory>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
#include <generated/BaseParser.hpp> // Generated by Bison
#pragma clang diagnostic pop

#include "../Exceptions/ParseError.hpp"
#include "../IR/Sentences/ISentenceNode.hpp"

namespace optifol
{

/**
 * @brief The first-order logic parser encapsulates the raw Bison-generated parser and provides various safety and
 *  convenience mechanisms.
 */
class FOLParser:
    public impl::BaseParser
{
public:
    /**
     * @brief Instantiate a new first-order logic parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     */
    explicit FOLParser(FOLLexer * lexer):
        BaseParser(lexer)
    { }

    void error(const std::string& msg) override
    {
        throw ParseError(msg, 0); // TODO get bad column number
    }

    /**
     * @brief Reports a new fully parsed root sentence, typically from another parser-like source
     * @param sentenceNode The parsed FOL sentence
     */
    [[maybe_unused]] void register_sentence(std::unique_ptr<ISentenceNode>&& sentenceNode)
    {
        last_parsed = std::move(sentenceNode);
    }

    [[nodiscard]] std::unique_ptr<ISentenceNode> retrieve_sentence()
    {
        auto sentence = std::move(last_parsed);
        last_parsed = nullptr;
        return sentence;
    }

private:
    /**
     * @brief A strong reference to the last-parsed FOL sentence.
     */
    std::unique_ptr<ISentenceNode> last_parsed;
};

}

#endif
