/**
 * @file FOLParser.hpp
 * @brief Class declaration of the exposed first-order logic parser
 * @date 21st November 2024
 * @author Oliver Dixon <od641@york.ac.uk>
 * @warning This file depends on build-time generated source from Flex and Bison.
 */

#ifndef OPTIFOL_FOLPARSER_HPP
#define OPTIFOL_FOLPARSER_HPP

#include <memory>

#include <generated/BaseParser.hpp> // Generated by Bison

#include "AST/ISentenceNode.hpp"

namespace optifol
{

/**
 * @brief The first-order logic parser encapsulates the raw Bison-generated parser and provides various safety and
 *  convenience mechanisms.
 */
class FOLParser:
    public impl::BaseParser
{
public:
    /**
     * @brief Instantiate a new first-order logic parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     */
    explicit FOLParser(FOLLexer * lexer):
        BaseParser(lexer)
    { }

    int parse() override
    {
        if (impl::BaseParser::parse() == 0)
            std::cout << last_parsed->to_string() << std::endl;

        return 0;
    }

    void error(const std::string& msg) override
    {
        std::cerr << msg << std::endl;
    }

    /**
     * @brief Reports a new fully parsed root sentence, typically from another parser-like source
     * @param sentenceNode The parsed FOL sentence
     */
    [[maybe_unused]] void registerSentence(std::shared_ptr<ISentenceNode> sentenceNode)
    {
        last_parsed = std::move(sentenceNode);
    }

private:
    /**
     * @brief A strong reference to the last-parsed FOL sentence.
     */
    std::shared_ptr<ISentenceNode> last_parsed;
};

}

#endif //OPTIFOL_FOLPARSER_HPP
