/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification of the exposed Google Test results protocol parser
 * @date 2025-07-14
 * @author Oliver Dixon <od641@york.ac.uk>
 * @note This file depends on build-time generated source from Flex and Bison.
 */

#ifndef GOOGLETESTPARSER_HPP
#define GOOGLETESTPARSER_HPP

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
#include <generated/BaseGoogleTestParser.hpp> // Generated by Bison
#pragma clang diagnostic pop

#include <log4cxx/logger.h>

#include "../../Exceptions/ParseError.hpp"

namespace optifol
{
class TestResult;

class GoogleTestParser:
    public impl::BaseGoogleTestParser
{
public:
    /**
     * @brief Instantiate a new Google Test results protocol parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     */
    explicit GoogleTestParser(GoogleTestLexer * lexer):
        BaseGoogleTestParser(lexer)
    { }

    void error(const std::string& msg) override
    {
        Logging::get_logger({"UserTesting", "GoogleTestResultsParser"})->error(msg);
        throw ParseError(msg, 0); // TODO get bad column number
    }

    void add_result(std::unique_ptr<TestResult>&& test_result)
    {
        test_results.push_back(std::move(test_result));
    }

    std::vector<std::unique_ptr<TestResult>>&& steal_test_results() noexcept
    {
        return std::move(test_results);
    }

    const std::vector<std::unique_ptr<TestResult>>& observe_test_results() const noexcept
    {
        return test_results;
    }

private:
    std::vector<std::unique_ptr<TestResult>> test_results;
    std::string test_suite;
};

}

#endif
