/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification of the exposed Google Test results protocol parser
 * @date 2025-07-14
 * @author Oliver Dixon <od641@york.ac.uk>
 * @note This file depends on build-time generated source from Flex and Bison.
 */

#ifndef FOLPARSER_HPP
#define FOLPARSER_HPP

#include <memory>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
#include <generated/BaseGoogleTestParser.hpp> // Generated by Bison
#pragma clang diagnostic pop

#include "../Exceptions/ParseError.hpp"

namespace optifol
{

class GoogleTestParser:
    public impl::BaseGoogleTestParser
{
public:
    /**
     * @brief Instantiate a new Google Test results protocol parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     */
    explicit GoogleTestParser(GoogleTestLexer * lexer):
        BaseGoogleTestParser(lexer)
    { }

    void error(const std::string& msg) override
    {
        throw ParseError(msg, 0); // TODO get bad column number
    }
};

}

#endif
