/*
 * Copyright (c) All Rights Reserved
 * 2025 Oliver Dixon <od641@york.ac.uk>
 */

/**
 * @file
 * @brief Class specification of the exposed Google Test results protocol parser
 * @date 2025-07-14
 * @author Oliver Dixon <od641@york.ac.uk>
 * @note This file depends on build-time generated source from Flex and Bison.
 */

#ifndef GOOGLETESTPARSER_HPP
#define GOOGLETESTPARSER_HPP

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
#include <generated/BaseGoogleTestParser.hpp> // Generated by Bison
#pragma clang diagnostic pop

#include <log4cxx/logger.h>
#include <sigc++/slot.h>
#include "../../Exceptions/ParseError.hpp"
#include "../../DereferencingEqualityFunctor.hpp"
#include "../TestResult.hpp"

namespace optifol
{

class GoogleTestParser : public impl::BaseGoogleTestParser
{
public:
    /**
     * @brief Instantiate a new Google Test results protocol parser, to be supplied by the given lexer
     * @param lexer The Flex-created lexer with which the parser should be acquainted
     * @param push_callback The callback to which newly parsed TestResult objects should be sent
     */
    explicit GoogleTestParser(GoogleTestLexer *lexer, sigc::slot<void(std::unique_ptr<TestResult>&&)>&& push_callback) :
        BaseGoogleTestParser(lexer),
        push_callback(std::move(push_callback))
    {
    }

    void error(const std::string &msg) override
    {
        Logging::get_logger({"UserTesting", "GoogleTestResultsParser"})->error(msg);
        throw ParseError(msg, 0); // TODO get bad column number
    }

    void push_result(std::unique_ptr<TestResult> &&test_result) const
    {
        push_callback(std::move(test_result));
    }

    void add_pending_test_result(std::unique_ptr<TestResult> &&test_result)
    {
        pending_test_results.push_back(std::move(test_result));
    }

    std::unique_ptr<TestResult> steal_next_pending_result() noexcept
    {
        if (pending_test_results.empty())
            return nullptr;

        auto borrowed_result = std::move(pending_test_results.back());
        pending_test_results.pop_back();
        return borrowed_result;
    }

private:
    std::vector<std::unique_ptr<TestResult>> pending_test_results;

    sigc::slot<void(std::unique_ptr<TestResult>&&)> push_callback;
};

} // namespace optifol

#endif
